on:
  workflow_call:
jobs:
  start-doing-stuff:
    runs-on: self-hosted
    steps:
      - name: step one of doing more stuff
        id: example
        run: |
          echo "I am doing more stuff now"
